### ISSUE TITLE
it's fixed headerview not like the listview addheaderview()?

### ISSUE THREAD

**Issue by clarkshu1016** [maurycyw/HeaderGridView#2]
it's fixed headerview not like the listview addHeaderView() ?  how to solve it ?

**Comment by maurycyw** [comment]
device and version?

**Comment by clarkshu1016** [comment]
my device : galaxy nexus ,
my version : 4.3 
I need PullRefreshGridView with moving headerview ,not FixHeaderView, so I used   chrisbanes 's library  https://github.com/chrisbanes/Android-PullToRefresh/blob/master/sample/src/com/handmark/pulltorefresh/samples/PullToRefreshGridActivity.java  ,I replace GridView into HeaderGridView ,it's fixed but pull to refresh works well.

**Comment by clarkshu1016** [comment]
hi  maurycyw, I already solve this problem using ListView,writing a customer BaseAdapter works liking the GridViewAdapter.

**Comment by maurycyw** [comment]
sorry @vanshu for late / no response
